class Settings():

    VALID_EXTENTIONS_FOR_REST_LOGO = {'png'}
    SAVE_EXTENTION_FOR_REST_LOGO = 'png'
    VALID_SIZE_FOR_REST_LOGO = 512

    VALID_EXTENTIONS_FOR_DISH_PHOTO = {'png'}
    SAVE_EXTENTION_FOR_DISH_PHOTO = 'png'
    VALID_SIZE_FOR_DISH_PHOTO = [1024, 1024]

    VALID_EXTENTIONS_FOR_REST_BANNER = {'png'}
    SAVE_EXTENTION_FOR_REST_BANNER = 'png'
    VALID_SIZE_FOR_REST_BANNER = [700, 320]

    # # This will create a file in <app> FOLDER
    # SQLALCHEMY_DATABASE_URI = 'sqlite:///data.db'
    # SQLALCHEMY_TRACK_MODIFICATIONS = False
