"""empty message

Revision ID: 01fb0843a63c
Revises: a78d500f8259
Create Date: 2022-11-23 22:10:19.359787

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '01fb0843a63c'
down_revision = 'a78d500f8259'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order', sa.Column('delivery_fee', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('order', 'delivery_fee')
    # ### end Alembic commands ###
