"""empty message

Revision ID: a78d500f8259
Revises: 
Create Date: 2022-11-23 01:06:20.539448

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a78d500f8259'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('restaurant', sa.Column('free_delivery_price', sa.Integer(), nullable=True))
    op.add_column('restaurant', sa.Column('delivery_fee', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('restaurant', 'delivery_fee')
    op.drop_column('restaurant', 'free_delivery_price')
    # ### end Alembic commands ###
